### ISSUE TITLE
A URL shortener isn't a boilerplate

### ISSUE THREAD

**Issue by arthurvr** [melvin0008/awesome-projects-boilerplates#11]
> URL-Shortener URL shortener by Jeffrey Way.

A *URL shortener* isn't a boilerplate. Also it's strongly unadvisable to use something like this as a boilerplate as it's literally just made as a demo.

**Comment by melvin0008** [comment]
I started this repo thinking of adding boilerplates and small projects for people getting started in a particular technology. But now I feel i should be focused only on boilerplates. What do you think?

**Comment by arthurvr** [comment]
@melvin0008 Those two things are totally different topics. Only boilerplates, as the description of this list states:

> Boilerplates for mobile and web apps

**Comment by melvin0008** [comment]
Yup Will remove the projects and keep it focused to boilerplates . Thanks

**Comment by arthurvr** [comment]
Why did you close the issue? It's not fixed yet.

**Comment by melvin0008** [comment]
Sorry! A noob in open source. Will get used to all this :)

**Comment by melvin0008** [comment]
Fixed :+1:
