### ISSUE TITLE
Add some Yeoman generators

### ISSUE THREAD

**Issue by arthurvr** [melvin0008/awesome-projects-boilerplates#20]
https://github.com/yeoman and others.

**Comment by melvin0008** [comment]
There are many generators available. Any ideas where to add them? Or a link to yeoman at the top will suffice?

**Comment by arthurvr** [comment]
I'd just do both a link to the Yeoman site and also list some super high-quality generators in the list.

**Comment by melvin0008** [comment]
Cool I will do that

**Comment by melvin0008** [comment]
Btw is it okay if i add you as a collaborator?

**Comment by arthurvr** [comment]
I'm not really interesting in actively contributing, sorry.

**Comment by melvin0008** [comment]
It's okay . Not a problem :)

**Comment by melvin0008** [comment]
Added yeoman and generators
