### ISSUE TITLE
Rename `CONTRIBUTIONS.MD` to `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by arthurvr** [melvin0008/awesome-projects-boilerplates#5]
The standard name for contribution guidelines is `contributing.md`, not `CONTRIBUTIONS.MD`.

Then GitHub will display it when opening new issues too, similar to this:

![new_issue_ _lukasz-madon_awesome-remote-job](https://cloud.githubusercontent.com/assets/6025224/8376083/93b8c9fc-1c03-11e5-8eaa-da32b6b811a4.png)

Thanks for the awesome list!

**Comment by melvin0008** [comment]
Hey thanks for the changes!
